### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by SUFE-lxc** [bigmat18/QuoraClone#10]
I clone your project to vs but i don't know run which file.

**Comment by bigmat18** [comment]
To run the project follow this steps:

1. Fork the project and open a terminal inside it.
2. execute 'python3 -m venv .venv' to create a virtual enviroment
3. Now run the enviroment with le follow command 'source .venv/bin/activate'
4. Intall all packages with 'pip install -r requirements.txt'
5. Execute the migrations with "python manage.py makemigrations" and next "python manage.py migrate"
6. Create a user to navigate in the site with "python manage.py createsuperuser"
7. Start your backend with "python manage.py runserver"

Ok now you can use the backend, for frontend you should do this:
1. From main repository go into frontend with 'cd frontend'
2. Now you should install node_modules with this command 'npm install package.json'.
3. Build frontend with "npm run build".
4. And now you can run it with "npm run serve".

If there is some problem write me.
Enjoy :)

**Comment by SUFE-lxc** [comment]
OK! Appreciate it！！
